In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

In [ ]:
df=pd.read_csv('./insurance.csv')

# EDA

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.isnull().sum()

In [ ]:
df.columns

In [ ]:
numeric_coloumns=['age', 'bmi', 'children', 'charges']
for col in numeric_coloumns:
    plt.figure(figsize=(6,4))
    sns.histplot(df[col],kde=True,bins=20)

In [ ]:
sns.countplot(x='children', data=df)

In [ ]:
sns.countplot(x=df['sex'], data=df)

In [ ]:
sns.countplot(x=df['smoker'], data=df)

In [ ]:
for col in numeric_coloumns:
    plt.figure(figsize=(6,4))
    sns.boxplot(x=df[col])

In [ ]:
plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')

# Data Cleaning and Preprocessing

In [ ]:
df_cleaned=df.copy()

In [ ]:
df_cleaned.head()

In [ ]:
df_cleaned=df_cleaned.drop_duplicates(inplace=True)

In [ ]:
df.isnull().sum()

In [ ]:
df.dtypes

In [ ]:
df['sex'].value_counts()

In [ ]:
df['sex']=df['sex'].map({'male':0,'female':1})

In [ ]:
df.head()

In [ ]:
df['smoker'].value_counts()

In [ ]:
df['smoker']=df['smoker'].map({'yes':1,'no':0})

In [ ]:
df.rename(columns={
    'sex':'is_female',
    'smoker':'is_smoker'
},inplace=True)

In [ ]:
df.head()

In [ ]:
df['region'].value_counts()

In [ ]:
df_cleaned=df.copy()

In [ ]:
df=pd.get_dummies(df,columns=['region'],drop_first=True)

In [ ]:
df.head()

In [ ]:
df=df.astype(int)

In [ ]:
df.head()

# Feature Engineering and extraction

In [ ]:
df['bmi_category']=pd.cut(
    df['bmi'],
    bins=[0,18.5,24.9,29.9,float('inf')],
    labels=['Underweight','Normal','Overweight','Obesse']
)

In [ ]:
df

In [ ]:
df=pd.get_dummies(df,columns=['bmi_category'],drop_first=True)

In [ ]:
df.astype(int)

In [134]:
from sklearn.preprocessing import StandardScaler
cols=['age','bmi','children']
scaler=StandardScaler()
df[cols]=scaler.fit_transform(df[cols])

In [135]:
df

,age,is_female,bmi,children,is_smoker,charges,region_northwest,region_southeast,region_southwest,bmi_category_Normal,bmi_category_Overweight,bmi_category_Obesse
0,-1.438764,1,-0.518122,-0.908614,1,16884,0,0,1,False,True,False
1,-1.509965,0,0.462657,-0.078767,0,1725,0,1,0,False,False,True
2,-0.797954,0,0.462657,1.580926,0,4449,0,1,0,False,False,True
3,-0.441948,0,-1.335438,-0.908614,0,21984,1,0,0,True,False,False
4,-0.513149,0,-0.354659,-0.908614,0,3866,1,0,0,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1333,0.768473,0,-0.027733,1.580926,0,10600,1,0,0,False,False,True
1334,-1.509965,1,0.135731,-0.908614,0,2205,0,0,0,False,False,True
1335,-1.509965,1,0.953046,-0.908614,0,1629,0,1,0,False,False,True
1336,-1.296362,1,-0.845048,-0.908614,0,2007,0,0,1,False,True,False
1337,1.551686,1,-0.191196,-0.908614,1,29141,1,0,0,False,True,False

In [142]:
from scipy.stats import pearsonr

selected_features=['age',	'is_female'	,'bmi'	,'children'	,'is_smoker',	'charges'	,'region_northwest'	,'region_southeast'	,'region_southwest',	'bmi_category_Normal',	'bmi_category_Overweight'	,'bmi_category_Obesse']
correlation={
    feature:pearsonr(df[feature],df['charges'])[0]
    for feature in selected_features
}
correlation_df=pd.DataFrame(list(correlation.items()),columns=['Feature','Pearson Correlation'])
correlation_df.sort_values(by='Pearson Correlation',ascending=False)

                    Feature  Pearson Correlation
5                   charges             1.000000
4                 is_smoker             0.787251
0                       age             0.299009
11      bmi_category_Obesse             0.199533
2                       bmi             0.196188
7          region_southeast             0.073981
3                  children             0.067999
6          region_northwest            -0.039905
8          region_southwest            -0.043210
1                 is_female            -0.057293
9       bmi_category_Normal            -0.103679
10  bmi_category_Overweight            -0.120084