## 1.Importing Pandas

In [146]:
import pandas as pd

## 2.Creating a DataFrame from a CSV file

In [147]:
df=pd.read_csv('../insurance.csv')
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

## 3. Opening a csv using Url

In [148]:
import requests 
from io import StringIO

url="https://gist.githubusercontent.com/dsternlicht/74020ebfdd91a686d71e785a79b318d4/raw/d3104389ba98a8605f8e641871b9ce71eff73f7e/chartsninja-data-1.csv"
##just telling that request go through this headers
headers={"User-Agents":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14;rv:66.0) Gecko/20100101 Firefox/66.0"}
req=requests.get(url,headers=headers)
data =StringIO(req.text)
pd.read_csv(data)

   Dataset 1   Dataset 2   Dataset 3
0        100         200         300
1        120         240         210
2        320         140         310

## 4. Set Parameters when creating a DataFrame

In [149]:
pd.read_csv('./file.tsv',sep='\t',names=['a','b','c','d'])
## if tsv instead of csv the do above

                    a       b    c            d
0       a   b   c   d     NaN  NaN          NaN
1                   0    50.0  5.0  881250949.0
2                   0   172.0  5.0  881250949.0
3                   0   133.0  1.0  881250949.0
4                 196   242.0  3.0  881250949.0
...               ...     ...  ...          ...
99999             880   476.0  3.0  880175444.0
100000            716   204.0  5.0  879795543.0
100001            276  1090.0  1.0  874795795.0
100002             13   225.0  2.0  882399156.0
100003             12   203.0  3.0  879959583.0

[100004 rows x 4 columns]

## 5.Index COl Parameter

In [150]:
# pd.read_csv('./file.tsv',index_col='a')

6. Header Parameter

In [151]:
# pd.read_csv('test.csv',header=1);
## used when coloum names are used as params

In [152]:
## Use_cols parameter

In [153]:
# pd.read_csv('../insurance.csv',usecols=[''])

Squeze params

In [154]:
# just use squeeze=true

Skip rows and nrows params

In [155]:
pd.read_csv('../insurance.csv',skiprows=[0,1],nrows=100)

    18    male   33.77  1   no  southeast    1725.5523
0   28    male  33.000  3   no  southeast   4449.46200
1   33    male  22.705  0   no  northwest  21984.47061
2   32    male  28.880  0   no  northwest   3866.85520
3   31  female  25.740  0   no  southeast   3756.62160
4   46  female  33.440  1   no  southeast   8240.58960
..  ..     ...     ... ..  ...        ...          ...
95  55    male  38.280  0   no  southeast  10226.28420
96  56    male  19.950  0  yes  northeast  22412.64850
97  38    male  19.300  0  yes  southwest  15820.69900
98  41  female  31.600  0   no  southwest   6186.12700
99  30    male  25.460  0   no  northeast   3645.08940

[100 rows x 7 columns]

Encodding PArams

Skip Bad Lines

In [156]:
# pd.read_csv('../insurance.csv',sep=';',error_bad_lines=False)

dtypes Params

In [157]:
## used to convert wroong used data types

In [158]:
# pd.read_csv('../insurance.csv',dtype={'target':int})

Handling dates

In [159]:
# use parse_dates=['date']

Convertors

In [160]:
def rename(name):
    if name=="Royal Challengers Bangalore":
        return "RCB"
    else:
        return name

In [161]:
rename("Royal Challengers Bangalore")

'RCB'

In [162]:
# pd.read_csv('../insurance.csv',converters={'team1':rename})

na_values params

In [ ]:
## used when NAN values are there 
## some times there are empty values instead of nan something else is theere examp:' or somthing
## else so just replace that with NAN using below 
# just use na_values=['Male']

LOading a huge dataset in chunks

In [165]:
dfs=pd.read_csv('../insurance.csv',chunksize=100)
for chunks in dfs:
    print(chunks.shape)

(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(100, 7)
(38, 7)