In [1]:
import numpy as np
import pandas as pd

In [2]:
data =pd.read_csv('./play_tennis.csv')
data.head()
data.drop(columns=['day'],inplace=True)

In [3]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [5]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [6]:
py=9/14
pn=5/14

In [8]:
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [9]:
Pon=0
prn=2/5
psn=3/5

poy=4/9
pry=3/9
psy=2/9

In [11]:
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [12]:
PcoolNo=1/5
PHotNo=2/5
PmildNo=2/5

PcoolYes=3/9
PHotYes=2/9
PmildYes=4/9

In [13]:
pd.crosstab(data['humidity'],data['play'])
PhighNo=4/5
PNormalNo=1/5
PHighYes=3/9
PNormalYes=6/9

In [15]:
pd.crosstab(data['wind'],data['play'])
PTrueNo=3/5
PFalseNo=2/5
PTrueYes=3/9
PFalseYes=6/9

In [16]:
#Outlook=Sunny,Temp=Cool,Humidity=High,Wind=True
PNo=Pon*PHotNo*PhighNo*PTrueNo*pn
print(PNo)

0.0